### ISSUE TITLE
Fix datapusher configuration

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckan-docker-dcatapit#15]
Datapusher needs to call CKAN API, and it seems it's pointing to localhost:5000.
Integration between ckan and datapusher must be fixed.

Here some logs about it:
```bash
 docker-compose logs datapusher
```
returns
```
[...]
datapusher-dev  | spawned uWSGI http 1 (pid: 16)
datapusher-dev  | *** running gevent loop engine [addr:0x560b2b250d30] ***
datapusher-dev  | Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
datapusher-dev  | Traceback (most recent call last):
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
datapusher-dev  |     conn = connection.create_connection(
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
datapusher-dev  |     raise err
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
datapusher-dev  |     sock.connect(sa)
datapusher-dev  | ConnectionRefusedError: [Errno 111] Connection refused
datapusher-dev  | 
datapusher-dev  | During handling of the above exception, another exception occurred:
datapusher-dev  | 
datapusher-dev  | Traceback (most recent call last):
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
datapusher-dev  |     httplib_response = self._make_request(
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
datapusher-dev  |     conn.request(method, url, **httplib_request_kw)
datapusher-dev  |   File "/usr/lib/python3.8/http/client.py", line 1252, in request
datapusher-dev  |     self._send_request(method, url, body, headers, encode_chunked)
datapusher-dev  |   File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
datapusher-dev  |     self.endheaders(body, encode_chunked=encode_chunked)
datapusher-dev  |   File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
datapusher-dev  |     self._send_output(message_body, encode_chunked=encode_chunked)
datapusher-dev  |   File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
datapusher-dev  |     self.send(msg)
datapusher-dev  |   File "/usr/lib/python3.8/http/client.py", line 947, in send
datapusher-dev  |     self.connect()
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
datapusher-dev  |     conn = self._new_conn()
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
datapusher-dev  |     raise NewConnectionError(
datapusher-dev  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd87f49a4c0>: Failed to establish a new connection: [Errno 111] Connection refused
datapusher-dev  | 
datapusher-dev  | During handling of the above exception, another exception occurred:
datapusher-dev  | 
datapusher-dev  | Traceback (most recent call last):
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
datapusher-dev  |     resp = conn.urlopen(
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
datapusher-dev  |     retries = retries.increment(
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
datapusher-dev  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
datapusher-dev  | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/3/action/resource_show (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd87f49a4c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
datapusher-dev  | 
datapusher-dev  | During handling of the above exception, another exception occurred:
datapusher-dev  | 
datapusher-dev  | Traceback (most recent call last):
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/apscheduler/scheduler.py", line 512, in _run_job
datapusher-dev  |     retval = job.func(*job.args, **job.kwargs)
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/datapusher/jobs.py", line 345, in push_to_datastore
datapusher-dev  |     resource = get_resource(resource_id, ckan_url, api_key)
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/datapusher/jobs.py", line 291, in get_resource
datapusher-dev  |     r = requests.post(url,
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/requests/api.py", line 119, in post
datapusher-dev  |     return request('post', url, data=data, json=json, **kwargs)
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
datapusher-dev  |     return session.request(method=method, url=url, **kwargs)
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
datapusher-dev  |     resp = self.send(prep, **send_kwargs)
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
datapusher-dev  |     r = adapter.send(request, **kwargs)
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
datapusher-dev  |     raise ConnectionError(e, request=request)
datapusher-dev  | requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/3/action/resource_show (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd87f49a4c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by etj** [comment]
After fixing the config, another error arise:
```
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/apscheduler/scheduler.py", line 239, in _notify_listeners
datapusher-dev  |     cb(event)
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/ckanserviceprovider/web.py", line 189, in job_listener
datapusher-dev  |     db.mark_job_as_errored(job_id, error_object)
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/ckanserviceprovider/db.py", line 413, in mark_job_as_errored
datapusher-dev  |     _update_job(job_id, update_dict)
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/ckanserviceprovider/db.py", line 348, in _update_job
datapusher-dev  |     job_dict["error"] = json.dumps(job_dict["error"])
datapusher-dev  |   File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
datapusher-dev  |     return _default_encoder.encode(obj)
datapusher-dev  |   File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
datapusher-dev  |     chunks = self.iterencode(o, _one_shot=True)
datapusher-dev  |   File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
datapusher-dev  |     return _iterencode(o, 0)
datapusher-dev  |   File "/usr/lib/python3.8/json/encoder.py", line 179, in default
datapusher-dev  |     raise TypeError(f'Object of type {o.__class__.__name__} '
datapusher-dev  | TypeError: Object of type Response is not JSON serializable
datapusher-dev  | Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
datapusher-dev  | Traceback (most recent call last):
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/apscheduler/scheduler.py", line 512, in _run_job
datapusher-dev  |     retval = job.func(*job.args, **job.kwargs)
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/datapusher/jobs.py", line 450, in push_to_datastore
datapusher-dev  |     existing = datastore_resource_exists(resource_id, api_key, ckan_url)
datapusher-dev  |   File "/usr/lib/python3.8/site-packages/datapusher/jobs.py", line 237, in datastore_resource_exists
datapusher-dev  |     raise HTTPError(
datapusher-dev  | datapusher.jobs.HTTPError: <unprintable HTTPError object>
```

**Comment by etj** [comment]
It seems that the error was already found [here](https://github.com/geosolutions-it/ckan-docker-dcatapit/issues/1#issuecomment-962932931)
